services:
  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      POSTGRES_DB: ${POSTGRESQL_DATABASE}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    ports:
      - ${HOST_POSTGRESQL_PORT}:${POSTGRESQL_PORT}
    labels:
      - "org.springframework.boot.service-connection=postgres"